name: Deploy Staging

on:
  push:
    branches:
    - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Make build destination directory
        run: mkdir -vp ~/www/repository-name

    - name: Jekyll Build
      uses: gha-utilities/jekyll-build@v0.0.8
      with:
        source: ./
        destination: ~/www/repository-name

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "~/www/repository-name"
        target: "/var/www/html/staging/"