name: Deploy Staging

on:
  pull_request:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Make build destination directory
        run: mkdir -vp ~/www/portfolio-website

      - name: Jekyll Build
        uses: gha-utilities/jekyll-build@v0.0.8
        with:
          source: ./
          destination: ~/www/portfolio-website

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "~/www/portfolio-website"
          target: "/var/www/html/staging/"