name: Post to socials

on: workflow_dispatch

jobs:
  social_post:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      # with:
      #   since_last_remote_commit: true
      with:
        files: |
          _posts/**

    - name: Post all new posts
      if: steps.changed-files.outputs.any_changed == 'true'
      env:
        ALL_NEW_POSTS: ${{ steps.changed-files.outputs.added_files }}
      run: |
        for file in ${ALL_NEW_POSTS}; do
          blog=${file:10:-3}
          echo $blog
        done
        
        curl -X POST -d "{\"status\":\"https://hughevans.dev/$blog/\", \
        \"media_ids\":null,\"poll\":null}" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{secrets.MASTODON_USER_TOKEN}}" \
        "https://hachyderm.io/api/v1/statuses"
